objects/Product_History__c/Product_History__c.object-meta.xml
<CustomObject>
    <label>Product History</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product_History__c/fields/Last_Update__c.field-meta.xml
<CustomField>
    <fullName>Last_Update__c</fullName>
    <label>Last Update</label>
    <type>Date</type>
</CustomField>

objects/Product_History__c/fields/Nett_Weight__c.field-meta.xml
<CustomField>
    <fullName>Nett_Weight__c</fullName>
    <label>Nett Weight</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

objects/Product_History__c/fields/Period01__c.field-meta.xml
<CustomField>
    <fullName>Period01__c</fullName>
    <label>Period01</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Product_History__c/fields/Period02__c.field-meta.xml
<CustomField>
    <fullName>Period02__c</fullName>
    <label>Period02</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Product_History__c/fields/Period03__c.field-meta.xml
<CustomField>
    <fullName>Period03__c</fullName>
    <label>Period03</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Product_History__c/fields/Period04__c.field-meta.xml
<CustomField>
    <fullName>Period04__c</fullName>
    <label>Period04</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Product_History__c/fields/Period05__c.field-meta.xml
<CustomField>
    <fullName>Period05__c</fullName>
    <label>Period05</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Product_History__c/fields/Period06__c.field-meta.xml
<CustomField>
    <fullName>Period06__c</fullName>
    <label>Period06</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Product_History__c/fields/Period07__c.field-meta.xml
<CustomField>
    <fullName>Period07__c</fullName>
    <label>Period07</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Product_History__c/fields/Period08__c.field-meta.xml
<CustomField>
    <fullName>Period08__c</fullName>
    <label>Period08</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Product_History__c/fields/Period09__c.field-meta.xml
<CustomField>
    <fullName>Period09__c</fullName>
    <label>Period09</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Product_History__c/fields/Period10__c.field-meta.xml
<CustomField>
    <fullName>Period10__c</fullName>
    <label>Period10</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Product_History__c/fields/Period11__c.field-meta.xml
<CustomField>
    <fullName>Period11__c</fullName>
    <label>Period11</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Product_History__c/fields/Product_BU__c.field-meta.xml
<CustomField>
    <fullName>Product_BU__c</fullName>
    <label>Product BU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Product_History__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <label>Product Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Product_History__c/fields/Quantity01__c.field-meta.xml
<CustomField>
    <fullName>Quantity01__c</fullName>
    <label>Quantity01</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Product_History__c/fields/Quantity02__c.field-meta.xml
<CustomField>
    <fullName>Quantity02__c</fullName>
    <label>Quantity02</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Product_History__c/fields/Quantity03__c.field-meta.xml
<CustomField>
    <fullName>Quantity03__c</fullName>
    <label>Quantity03</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Product_History__c/fields/Quantity04__c.field-meta.xml
<CustomField>
    <fullName>Quantity04__c</fullName>
    <label>Quantity04</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Product_History__c/fields/Quantity05__c.field-meta.xml
<CustomField>
    <fullName>Quantity05__c</fullName>
    <label>Quantity05</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Product_History__c/fields/Quantity06__c.field-meta.xml
<CustomField>
    <fullName>Quantity06__c</fullName>
    <label>Quantity06</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Product_History__c/fields/Quantity07__c.field-meta.xml
<CustomField>
    <fullName>Quantity07__c</fullName>
    <label>Quantity07</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Product_History__c/fields/Quantity08__c.field-meta.xml
<CustomField>
    <fullName>Quantity08__c</fullName>
    <label>Quantity08</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Product_History__c/fields/Quantity09__c.field-meta.xml
<CustomField>
    <fullName>Quantity09__c</fullName>
    <label>Quantity09</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Product_History__c/fields/Quantity10__c.field-meta.xml
<CustomField>
    <fullName>Quantity10__c</fullName>
    <label>Quantity10</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Product_History__c/fields/Quantity11__c.field-meta.xml
<CustomField>
    <fullName>Quantity11__c</fullName>
    <label>Quantity11</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Product_History__c/fields/Unit_Of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_Of_Measure__c</fullName>
    <label>Unit Of Measure</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

classes/chartController.cls
public class chartController {
    @AuraEnabled(cacheable=true)
    //public static List<Product_History__c> getobjData(String prodId){
    public static List<dataSetRecords> getobjData(){
        /*return [SELECT Name__c,Product_Code__c,Nett_Weight__c,Unit_Of_Measure__c,Last_Update__c,Product_BU__c,
        Period__c,Period01__c,Period02__c,Period03__c,Period04__c,Period05__c,Period06__c,Period07__c,Period08__c,Period09__c,Period10__c,Period11__c,
        Quantity__c,Quantity01__c,Quantity02__c,Quantity03__c,Quantity04__c,Quantity05__c,Quantity06__c,Quantity07__c,Quantity08__c,Quantity09__c,Quantity10__c,Quantity11__c
        FROM Product_History__c];// where id=:prodId];// WHERE CloseDate >= LAST_N_DAYS:30 AND StageName = 'Closed Won'];*/
        Map<String,List<Decimal>> finalList =  new Map<String,List<Decimal>>();
        for(Product_History__c ph : [SELECT Name,Product_Code__c,Nett_Weight__c,Unit_Of_Measure__c,Last_Update__c,Product_BU__c,Period__c,Period01__c,Period02__c,Period03__c,Period04__c,Period05__c,Period06__c,Period07__c,Period08__c,Period09__c,Period10__c,Period11__c,Quantity__c,Quantity01__c,Quantity02__c,Quantity03__c,Quantity04__c,Quantity05__c,Quantity06__c,Quantity07__c,Quantity08__c,Quantity09__c,Quantity10__c,Quantity11__c
        FROM Product_History__c])
        {
            if(finalList.containsKey(ph.Period__c)) {
                List<Decimal> periodValues = finalList.get(ph.Period__c);
                periodValues.add(ph.Quantity__c);
                finalList.put(ph.Period__c, periodValues);
            } else {
                finalList.put(ph.Period__c, new List<Decimal> { ph.Quantity__c });
            }
            if(finalList.containsKey(ph.Period01__c)) {
                List<Decimal> periodValues = finalList.get(ph.Period01__c);
                periodValues.add(ph.Quantity01__c);
                finalList.put(ph.Period01__c, periodValues);
            } else {
                finalList.put(ph.Period01__c, new List<Decimal> { ph.Quantity01__c });
            }
            if(finalList.containsKey(ph.Period02__c)) {
                List<Decimal> periodValues = finalList.get(ph.Period02__c);
                periodValues.add(ph.Quantity02__c);
                finalList.put(ph.Period02__c, periodValues);
            } else {
                finalList.put(ph.Period02__c, new List<Decimal> { ph.Quantity02__c });
            }
            if(finalList.containsKey(ph.Period03__c)) {
                List<Decimal> periodValues = finalList.get(ph.Period03__c);
                periodValues.add(ph.Quantity03__c);
                finalList.put(ph.Period03__c, periodValues);
            } else {
                finalList.put(ph.Period03__c, new List<Decimal> { ph.Quantity03__c });
            }
            if(finalList.containsKey(ph.Period04__c)) {
                List<Decimal> periodValues = finalList.get(ph.Period04__c);
                periodValues.add(ph.Quantity04__c);
                finalList.put(ph.Period04__c, periodValues);
            } else {
                finalList.put(ph.Period04__c, new List<Decimal> { ph.Quantity04__c });
            }
            if(finalList.containsKey(ph.Period05__c)) {
                List<Decimal> periodValues = finalList.get(ph.Period05__c);
                periodValues.add(ph.Quantity05__c);
                finalList.put(ph.Period05__c, periodValues);
            } else {
                finalList.put(ph.Period05__c, new List<Decimal> { ph.Quantity05__c });
            }
            if(finalList.containsKey(ph.Period06__c)) {
                List<Decimal> periodValues = finalList.get(ph.Period06__c);
                periodValues.add(ph.Quantity06__c);
                finalList.put(ph.Period06__c, periodValues);
            } else {
                finalList.put(ph.Period06__c, new List<Decimal> { ph.Quantity06__c });
            }
            if(finalList.containsKey(ph.Period07__c)) {
                List<Decimal> periodValues = finalList.get(ph.Period07__c);
                periodValues.add(ph.Quantity07__c);
                finalList.put(ph.Period07__c, periodValues);
            } else {
                finalList.put(ph.Period07__c, new List<Decimal> { ph.Quantity07__c });
            }
            if(finalList.containsKey(ph.Period08__c)) {
                List<Decimal> periodValues = finalList.get(ph.Period08__c);
                periodValues.add(ph.Quantity08__c);
                finalList.put(ph.Period08__c, periodValues);
            } else {
                finalList.put(ph.Period08__c, new List<Decimal> { ph.Quantity08__c });
            }
            if(finalList.containsKey(ph.Period09__c)) {
                List<Decimal> periodValues = finalList.get(ph.Period09__c);
                periodValues.add(ph.Quantity09__c);
                finalList.put(ph.Period09__c, periodValues);
            } else {
                finalList.put(ph.Period09__c, new List<Decimal> { ph.Quantity09__c });
            }
            if(finalList.containsKey(ph.Period10__c)) {
                List<Decimal> periodValues = finalList.get(ph.Period10__c);
                periodValues.add(ph.Quantity10__c);
                finalList.put(ph.Period10__c, periodValues);
            } else {
                finalList.put(ph.Period10__c, new List<Decimal> { ph.Quantity10__c });
            }
            if(finalList.containsKey(ph.Period11__c)) {
                List<Decimal> periodValues = finalList.get(ph.Period11__c);
                periodValues.add(ph.Quantity11__c);
                finalList.put(ph.Period11__c, periodValues);
            } else {
                finalList.put(ph.Period11__c, new List<Decimal> { ph.Quantity11__c });
            }
        }
        List<dataSetRecords> finalData = new List<dataSetRecords>();
        for(String str : finalList.keySet())
        {
            dataSetRecords dsr = new dataSetRecords(str,finalList.get(str));
            //dsr.label = str;
            //dsr.qty.addall(finalList.get(str));
            finalData.add(dsr);
        }
        return finalData;
    }

    public with sharing class dataSetRecords {
        @AuraEnabled public String label {get;set;}
        @AuraEnabled public List<Decimal> qty {get;set;}
        public dataSetRecords(String label ,List<Decimal> count){
            this.label  = label ;
            this.qty = count ;
        }
    }
}